name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  macos_build:
    name: MacOS (${{ matrix.OS }})
    strategy:
      fail-fast: true
      matrix:
        OS: ["macos-13", "macos-14"]
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - uses: coursier/cache-action@v6

      - uses: VirtusLab/scala-cli-setup@main
        with:
          power: true

      - name: Build the binary
        run: make platform-bin

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: out/release/*
          name: ${{ matrix.os }}-binaries
          if-no-files-found: error

  linux_build:
    name: Linux (${{ matrix.OS }})
    strategy:
      fail-fast: true
      matrix:
        OS: ["ubuntu-22.04", "ubuntu-22.04-arm"]
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - uses: coursier/cache-action@v6

      - uses: VirtusLab/scala-cli-setup@main
        with:
          power: true

      - name: Build the binary
        run: make platform-bin

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: out/release/*
          name: ${{ matrix.os }}-binaries
          if-no-files-found: error

  windows_build:
    name: Windows
    strategy:
      fail-fast: false
    runs-on: windows-2019
    env:
      LLVM_BIN: 'C:\Program Files\LLVM\bin'
      LLVM_VERSION: "20.1.0"
    steps:
      # This step is important to make sure scalafmt
      # checks don't fail
      - name: Setup git config
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      # See https://github.com/scala-native/scala-native/blob/master/.github/actions/windows-setup-env/action.yml#L14 SN_RELE
      # for details
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 4GB
          maximum-size: 16GB

      - uses: coursier/cache-action@v6

      - uses: VirtusLab/scala-cli-setup@main
        with:
          power: true

      - name: Install clang and make
        shell: pwsh
        run: |
          choco install llvm --version="$Env:LLVM_VERSION" --allow-downgrade
          choco install make
          clang --version

      - name: Build binary (windows)
        run: make platform-bin
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: out/release/*
          name: windows-binaries
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [linux_build, windows_build, macos_build]
    name: Upload binaries to release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download binaries
        uses: actions/download-artifact@v4
        id: download
        with:
          path: binaries

      - name: List downloaded binaries
        run: ls -R binaries

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${{steps.download.outputs.download-path}}/**/*"

  mergify-build-checkpoint:
    runs-on: ubuntu-latest
    needs: [linux_build, windows_build, macos_build]
    steps:
      - name: I only exist to please Mergify :(
        run: echo "It's a sad existence but necessary"
